# Generated by Django 3.2.7 on 2021-11-25 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20211125_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripción',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
