# Generated by Django 3.2.7 on 2021-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripción',
            field=models.CharField(max_length=600),
        ),
    ]
