# Generated by Django 3.2.7 on 2021-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripción',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
